replicaCount: 1

image:
  repository: kubevision
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true
  clusterWide: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: kubevision.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce

env:
  NEXTAUTH_SECRET: ""
  NEXTAUTH_URL: ""

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podSecurityContext:
  fsGroup: 1001
securityContext:
  runAsUser: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
