{{- if .Values.env.NEXTAUTH_SECRET -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevision.fullname" . }}
  labels:
    {{- include "kubevision.labels" . | nindent 4 }}
type: Opaque
data:
  nextauth-secret: {{ .Values.env.NEXTAUTH_SECRET | b64enc | quote }}
{{- end }}
