import { NextResponse } from "next/server";
import { Octokit } from "octokit";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

interface PlanResource {
  kind: string;
  label: string;
  config: Record<string, string>;
}

export async function POST(request: Request) {
  try {
    const { context, resources, title, description } = await request.json();

    if (!context) {
      return NextResponse.json({ error: "context is required" }, { status: 400 });
    }
    if (!resources || !Array.isArray(resources) || resources.length === 0) {
      return NextResponse.json({ error: "resources array is required" }, { status: 400 });
    }

    const config = await prisma.gitConfig.findUnique({
      where: { contextName: context },
    });

    if (!config || !config.githubToken) {
      return NextResponse.json(
        { error: "GitHub not configured for this cluster. Set it up in Cluster Settings > GitOps." },
        { status: 400 }
      );
    }

    const octokit = new Octokit({ auth: config.githubToken });
    const owner = config.repoOwner;
    const repo = config.repoName;
    const baseBranch = config.baseBranch;
    const targetPath = config.targetPath.endsWith("/") ? config.targetPath : config.targetPath + "/";

    const branchName = `kubevision/plan-${Date.now()}`;

    const { data: refData } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${baseBranch}`,
    });
    const baseSha = refData.object.sha;

    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    const yamls: string[] = [];
    for (const res of resources as PlanResource[]) {
      const yaml = buildYaml(res, context);
      const fileName = `${res.kind.toLowerCase()}-${res.label.toLowerCase().replace(/[^a-z0-9-]/g, "-")}.yaml`;
      const filePath = `${targetPath}${fileName}`;

      let existingSha: string | undefined;
      try {
        const { data: existing } = await octokit.rest.repos.getContent({
          owner,
          repo,
          path: filePath,
          ref: branchName,
        });
        if (!Array.isArray(existing) && existing.type === "file") {
          existingSha = existing.sha;
        }
      } catch {
        // file doesn't exist yet
      }

      await octokit.rest.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: filePath,
        message: `Add ${res.kind}/${res.label} from KubeVision planner`,
        content: Buffer.from(yaml).toString("base64"),
        branch: branchName,
        ...(existingSha ? { sha: existingSha } : {}),
      });

      yamls.push(filePath);
    }

    const prTitle = title || `[KubeVision] Plan: ${resources.length} resource(s) for ${context}`;
    const resourceList = (resources as PlanResource[])
      .map((r) => `- **${r.kind}**: \`${r.label}\``)
      .join("\n");

    const prBody = `## KubeVision Planned Deployment

${description || "Resources planned via KubeVision architecture planner."}

### Resources (${resources.length})
${resourceList}

### Files Modified
${yamls.map((f) => `- \`${f}\``).join("\n")}

### Cluster Context
\`${context}\`

---
*Generated by KubeVision GitOps Integration*`;

    const { data: pr } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: baseBranch,
    });

    return NextResponse.json({
      success: true,
      prNumber: pr.number,
      prUrl: pr.html_url,
      branch: branchName,
      filesCreated: yamls,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create PR";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

function buildYaml(resource: PlanResource, namespace: string): string {
  const kind = resource.kind;
  const name = resource.label.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  const cfg = resource.config || {};

  switch (kind) {
    case "Deployment":
      return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: ${cfg.namespace || "default"}
  labels:
    app: ${name}
    managed-by: kubevision
spec:
  replicas: ${cfg.replicas || "1"}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: ${name}
          image: ${cfg.image || "nginx:latest"}
          ports:
            - containerPort: ${cfg.port || "80"}
`;

    case "Service":
      return `apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${cfg.namespace || "default"}
  labels:
    app: ${name}
    managed-by: kubevision
spec:
  type: ${cfg.type || "ClusterIP"}
  ports:
    - port: ${cfg.port || "80"}
      targetPort: ${cfg.targetPort || cfg.port || "80"}
      protocol: TCP
  selector:
    app: ${cfg.selector || name}
`;

    case "Ingress":
      return `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${name}
  namespace: ${cfg.namespace || "default"}
  labels:
    managed-by: kubevision
spec:
  rules:
    - host: ${cfg.host || `${name}.local`}
      http:
        paths:
          - path: ${cfg.path || "/"}
            pathType: Prefix
            backend:
              service:
                name: ${cfg.serviceName || name}
                port:
                  number: ${cfg.port || "80"}
`;

    case "ConfigMap":
      return `apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}
  namespace: ${cfg.namespace || "default"}
  labels:
    managed-by: kubevision
data: {}
`;

    case "PersistentVolumeClaim":
      return `apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${name}
  namespace: ${cfg.namespace || "default"}
  labels:
    managed-by: kubevision
spec:
  accessModes:
    - ${cfg.accessMode || "ReadWriteOnce"}
  resources:
    requests:
      storage: ${cfg.storage || "1Gi"}
`;

    default:
      return `apiVersion: v1
kind: ${kind}
metadata:
  name: ${name}
  namespace: ${cfg.namespace || "default"}
  labels:
    managed-by: kubevision
`;
  }
}
